### ISSUE TITLE
Duplicate rows

### ISSUE THREAD

**Issue by cpavloud** [emo-bon/observatory-piegetxo-crate#4]
In the water logsheets, EMOBON_PiEGetxo_Wa_210824_3um_blank and EMOBON_PiEGetxo_Wa_210824_0.2um_blank are appearing twice

**Comment by cpavloud** [comment]
In both sampling and measured files

**Comment by cpavloud** [comment]
@melinalou

**Comment by melinalou** [comment]
done

**Comment by cpavloud** [comment]
Please confirm if this change has also taken place in the google spreadsheets.

**Comment by melinalou** [comment]
confirmed
